addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.13.2")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.12.0")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.3.2")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "2.1.2")
addSbtPlugin("com.github.sbt" % "sbt-git" % "2.2.0")
addSbtPlugin("com.github.sbt" % "sbt-release" % "1.5.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.12.2")
