name: Test & Build
on: [push, pull_request]
env:
  SBT_OPTS: "-sbt-launch-dir .sbt/launchers -sbt-dir .sbt -ivy .ivy2 -Dsbt.color=true -Dscala.color=true"
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    container: uptane/ci:latest
    services:
      tuf-nginx:
        image: uptane/tuf-nginx:latest

      db:
        image: mariadb:10.4
        env:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "ota_tuf"
          MYSQL_USER: "ota_tuf"
          MYSQL_PASSWORD: "ota_tuf"
        # command:
        #     - --character-set-server=utf8
        #     - --collation-server=utf8_unicode_ci
        #     - --max_connections=1000

    env:
      DB_URL: "jdbc:mariadb://db:3306/ota_tuf"
      MTLS_REPOSERVER_URI: "https://tuf-nginx:8181/"

    steps:
      - uses: actions/checkout@v2
      - name: Cache sbt dependencies
        uses: actions/cache@v2
        with:
          path: |
            .sbt
            .ivy2
          key: ${{ runner.os }}-sbt-deps-1.5
      - run: ./deploy/gitlab-db-setup.sh mysql db
      - run: sbt clean ut:test
