name: Release
on:
  push:
    branches: [master, uptane-sm/ci-cd]
    tags: ["*"]

jobs:
  release-to-nexus:
    name: Release Jars
    runs-on: ubuntu-latest
    env:
#      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_USER: somethinguser
#      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_PASSWORD: somethingpass
      SBT_CREDENTIALS: .sonatype-credentials
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.8
      - uses: coursier/cache-action@v6
      - run: printf "realm=Sonatype Nexus Repository Manager\nhost=s01.oss.sonatype.org\nuser=${SONATYPE_USER}\npassword=${SONATYPE_PASSWORD}\n" > ${SBT_CREDENTIALS}
      - run: cat $SBT_CREDENTIALS
      - run: sbt +publish

  build-images:
    name: Build and Push Images
    runs-on: ubuntu-latest
#    needs: run-tests
#    container: uptane/ci:latest
    # env:
    #   SBT_OPTS: "-sbt-launch-dir .sbt/launchers -sbt-dir .sbt -ivy .ivy2 -Dsbt.color=true -Dscala.color=true"
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.8
      - name: Coursier cache
        uses: coursier/cache-action@v6
      # - name: Cache sbt dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       .sbt
      #       .ivy2
      #     key: ${{ runner.os }}-sbt-deps
      - run: sbt docker:publishLocal
      - run: docker tag advancedtelematic/tuf-reposerver:$GITHUB_SHA uptane/tuf-reposerver:$GITHUB_SHA
      - run: docker tag advancedtelematic/tuf-keyserver:$GITHUB_SHA uptane/tuf-keyserver:$GITHUB_SHA
      - run: docker push uptane/tuf-reposerver:$GITHUB_SHA
      - run: docker push uptane/tuf-keyserver:$GITHUB_SHA
